-- MySQL Script generated by MySQL Workbench
-- 03/25/17 20:19:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`casetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`casetas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`casetas` (
  `id_caseta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `numero_exterior` VARCHAR(20) NOT NULL,
  `colonia` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `codigo_postal` VARCHAR(20) NOT NULL,
  `estatus` INT NOT NULL DEFAULT 1,
  UNIQUE INDEX `idx1_cli_id_caseta` (`id_caseta` ASC),
  PRIMARY KEY (`id_caseta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`residencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`residencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`residencias` (
  `id_residencia` INT NOT NULL AUTO_INCREMENT,
  `familia` VARCHAR(100) NOT NULL,
  `id_caseta` INT NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `numero_exterior` VARCHAR(20) NOT NULL,
  `colonia` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `codigo_postal` VARCHAR(20) NOT NULL,
  `estatus` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_residencia`),
  UNIQUE INDEX `idx1_resi_id_residencia` (`id_residencia` ASC),
  CONSTRAINT `fidx1_resi_caseta`
    FOREIGN KEY (`id_caseta`)
    REFERENCES `mydb`.`casetas` (`id_caseta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `clave` BINARY(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `celular` VARCHAR(45) NULL,
  `max_vigilantes` INT NOT NULL DEFAULT 0,
  `id_residencia` INT NULL,
  `id_caseta` INT NULL,
  `tipo_usuario` INT NULL DEFAULT 99,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  `estatus_registro` INT NOT NULL DEFAULT 0,
  `estatus_logon` INT NOT NULL DEFAULT 0,
  `mkt_dogo` TINYINT(1) NULL DEFAULT 0,
  `mkt_mail` TINYINT(1) NULL DEFAULT 0,
  `mkt_whatsapp` TINYINT(1) NULL DEFAULT 0,
  `fecha_hr_alta` DATETIME NOT NULL DEFAULT getdate(),
  `fecha_hr_ultimo_acceso` DATETIME NOT NULL DEFAULT getdate(),
  UNIQUE INDEX `idx1_usu_id_usuario` (`id_usuarios` ASC),
  PRIMARY KEY (`id_usuarios`),
  CONSTRAINT `fdx1_usu_caseta`
    FOREIGN KEY (`id_caseta`)
    REFERENCES `mydb`.`casetas` (`id_caseta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fdx2_usu_residencia`
    FOREIGN KEY (`id_residencia`)
    REFERENCES `mydb`.`residencias` (`id_residencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contactos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contactos` (
  `id_contacto` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `empresa` VARCHAR(100) NULL,
  `placas` VARCHAR(50) NULL,
  `fecha_hr_alta` DATETIME NOT NULL DEFAULT getdate(),
  `estatus` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_contacto`),
  UNIQUE INDEX `id_contacto_UNIQUE` (`id_contacto` ASC),
  INDEX `idx1_conta_usuario` (`id_usuario` ASC),
  CONSTRAINT `fdx1_conta_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`citas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_residente` INT NOT NULL,
  `asunto` VARCHAR(2500) NOT NULL,
  `nombre_residencia` VARCHAR(100) NULL,
  `nombre_usuario` VARCHAR(100) NULL,
  `observaciones` VARCHAR(2500) NULL,
  `fecha_hr_cita` DATETIME NOT NULL,
  `estatus` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_cita`),
  UNIQUE INDEX `idx1_cita_id_cita` (`id_cita` ASC),
  INDEX `idx2_cita_id_usuario` (`id_usuario_residente` ASC),
  CONSTRAINT `fdx1_cita_usuario`
    FOREIGN KEY (`id_usuario_residente`)
    REFERENCES `mydb`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`citados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`citados` (
  `id_acceso` INT NOT NULL AUTO_INCREMENT,
  `id_cita` INT NOT NULL,
  `id_contacto` INT NOT NULL,
  `estatus` INT NULL DEFAULT 1,
  PRIMARY KEY (`id_acceso`),
  INDEX `idx3_citados_cita` (`id_cita` ASC),
  CONSTRAINT `idx1_citados_cita`
    FOREIGN KEY (`id_cita`)
    REFERENCES `mydb`.`citas` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx2_citados_contacto`
    FOREIGN KEY (`id_contacto`)
    REFERENCES `mydb`.`contactos` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registrocita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registrocita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registrocita` (
  `id_cita` INT NOT NULL,
  `id_acceso` INT NOT NULL,
  `secuencia_registro` INT NOT NULL,
  `nombe_contacto` VARCHAR(100) NULL,
  `comentario_poli` VARCHAR(1000) NULL,
  `id_usuario_poli` INT NULL,
  `fecha_hora_registro` DATETIME NULL DEFAULT getdate(),
  `estatus` INT NULL DEFAULT 1,
  INDEX `idx1_regcita_cita` (`id_cita` ASC),
  INDEX `idx2_regcita_acceso` (`id_acceso` ASC),
  INDEX `idx3_regcita_usuario` (`id_usuario_poli` ASC),
  CONSTRAINT `fdx1_regcita_id_acceso`
    FOREIGN KEY (`id_acceso`)
    REFERENCES `mydb`.`citados` (`id_acceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fdx1_regcita_id_cita`
    FOREIGN KEY (`id_cita`)
    REFERENCES `mydb`.`citas` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fdx2_regcita_id_cita`
    FOREIGN KEY (`id_cita`)
    REFERENCES `mydb`.`citados` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fdx1_regcita_id_usuarios`
    FOREIGN KEY (`id_usuario_poli`)
    REFERENCES `mydb`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`busquedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`busquedas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`busquedas` (
  `id_busqueda` INT NOT NULL,
  `tabla` VARCHAR(50) NOT NULL,
  `concepto` VARCHAR(50) NULL,
  `palabra` VARCHAR(50) NULL,
  INDEX `idx_bus_tabla` (`tabla` ASC),
  INDEX `idx_bus_concepto` (`concepto` ASC),
  INDEX `idx4_bus_palabra` (`palabra` ASC),
  CONSTRAINT `idx1_bus_id_busqueda`
    FOREIGN KEY (`id_busqueda`)
    REFERENCES `mydb`.`casetas` (`id_caseta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx2_bus_id_busqueda`
    FOREIGN KEY (`id_busqueda`)
    REFERENCES `mydb`.`residencias` (`id_residencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx3_bus_id_busqueda`
    FOREIGN KEY (`id_busqueda`)
    REFERENCES `mydb`.`contactos` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx4_bus_id_busqueda`
    FOREIGN KEY (`id_busqueda`)
    REFERENCES `mydb`.`residencias` (`id_residencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx5_bus_id_busqueda`
    FOREIGN KEY (`id_busqueda`)
    REFERENCES `mydb`.`casetas` (`id_caseta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pignorada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pignorada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pignorada` (
  `palabra` VARCHAR(50) NOT NULL,
  INDEX `idx1_pi_palabra` (`palabra` ASC),
  CONSTRAINT `fdx1_pi_palabra`
    FOREIGN KEY (`palabra`)
    REFERENCES `mydb`.`busquedas` (`palabra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
